version: '3.3'

services:

    db:
        image: mariadb:10.4     
        container_name: app-mariadb                
        ports:
            - "3320:3306"
        environment:
            MYSQL_ROOT_PASSWORD: helloWORLD123
            MYSQL_DATABASE: sp_odesi
            MYSQL_USER: root
            MYSQL_PASSWORD: helloWORLD123

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: app-phpmyadmin    
        depends_on:
            - db
        restart: always
        ports:
            - "8888:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db

    python:
        build: .        
        container_name: app-python      
        command: python sp_odesi.py
        restart: always        
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            MYSQL_HOST: db
            MYSQL_DATABASE: sp_odesi
            MYSQL_USER: root
            MYSQL_PASSWORD: helloWORLD123
            MYSQL_PORT: 3306
        
